image: node:latest

before_script:
  - npm install
  - bower install --allow-root
  - apt-get -y update
  - apt-get -y install ruby-full
  - gem install sass
  - gem install compass

stages:
  - build
  - test

cache:
  paths:
  - node_modules/

stages:

run_tests:
  script:
   - npm install
   - grunt test
